#pragma once

#define MPU6050_DEFAULT_ADDR 0x68

#define MPU_KALMAN_DEFAULT_UPDATE_HZ 200.0f
#define MPU_KALMAN_DEFAULT_Q_ANGLE 0.001f
#define MPU_KALMAN_DEFAULT_Q_BIAS 0.003f
#define MPU_KALMAN_DEFAULT_R_MEASURE 0.03f

// #define MPU_INCLUDE_MADGWICK

#define MPU_MAX_UPDATE_HZ 1000.0f
